### ISSUE TITLE
Изучить работу Celery и выбрать брокер сообщений для хранения задач

### ISSUE THREAD

**Issue by blindsphynx** [moevm/mse1h2024-coderunner#1]
Нужно разобраться в принципе работы очереди задач Celery. Celery сама по себе не хранит в себе задачи, поэтому необходимо использовать брокер сообщений. Предлагаю выбирать между Redis и RabbitMQ. Нужно провести небольшой сравнительный анализ и решить, какой брокер будем использовать. Создайте wiki-страничку и опишите там результаты анализа.

Существует также веб-приложение Flower, которое позволяет управлять кластерами Celery. Нужно также изучить и решить, насколько оно нам будет полезно. Результаты тоже можно оформить на wiki-страничке.

Материалы, которые можно изучить:
- [туториал 1](https://www.youtube.com/watch?v=fm4LTvMyiwE&ab_channel=%D0%90%D1%80%D1%82%D1%91%D0%BC%D0%A8%D1%83%D0%BC%D0%B5%D0%B9%D0%BA%D0%BE) по Celery + Flower + Redis
- [туториал 2](https://www.youtube.com/watch?v=mcX_4EvYka4&ab_channel=VeryAcademy) (здесь используется docker-compose, что также актуально для нас)
- [Monitor your Celery workers using Flower](https://medium.com/featurepreneur/flower-celery-monitoring-tool-50fba1c8f623)

**Comment by Fayzak** [comment]
В ходе кооперации с коллегой решили, что:

- Celery + Redis - исследует Тимофей
- Celery + RabbitMQ - исследует Егор
- Каждый посмотрит, что такое Flower

**Comment by Fayzak** [comment]
Закончили с Егором вики, по итогу решили, что будем использовать Celery + Redis + Flower
