### ISSUE TITLE
Документация сервера

### ISSUE THREAD

**Issue by blindsphynx** [moevm/mse1h2024-coderunner#19]
Добавить документацию к серверу на wiki, чтобы было понятно, как это саппортить в дальнейшем (указать ссылки на роуты, API JOBE и т.д.)

**Comment by jonx8** [comment]
Добавлена документация, описывающая имеющийся на данный момент функционал. К концу итерации документация будет обновлена

**Comment by jonx8** [comment]
Обновил документацию
