### ISSUE TITLE
Изучить API moodle, CodeRunner и JOBE и предложить аналогичные методы для приложения-обёртки

### ISSUE THREAD

**Issue by blindsphynx** [moevm/mse1h2024-coderunner#2]
- Нужно понять, на чём строится взаимодействие moodle + CodeRunner и JOBE, что они получают и возвращают как результат работы; 
- Найти, чем "торчит" наружу JOBE, и предложить метод/список методов для нашей обёртки, через которые moodle будет к ней обращаться точно так же, как к JOBE;
- Такой же список методов для обращения JOBE к moodle.

Не обязательно подробно описывать, что должны делать методы, пока достаточно на уровне "нужен такой-то метод, он должен принимать вот эти параметры и возвращать такое значение". Результаты оформить на wiki-странице.

**Comment by jonx8** [comment]
Подготовлена страница с описанием метода, на основе которого построено взаимодействие Jobe и Moodle.
