### ISSUE TITLE
Прототип (moodle + JOBE)

### ISSUE THREAD

**Issue by blindsphynx** [moevm/mse1h2024-coderunner#3]
Повторить текущий функционал. Установить moodle, подключить к нему CodeRunner, развернуть JOBE ([в докере](https://hub.docker.com/r/trampgeek/jobeinabox/)) и настроить их взаимодействие. Перед этим надо узнать, какая версия moodle сейчас используется на кафедре.

**Comment by MaksimOvchinnikov** [comment]
Версия Moodle, используемая на кафедре, - 3.8. При переходе на более поздние версии Moodle проблем с разработанной оберткой быть не должно, поскольку её единственная зависимость - это эндпоинты jobe сервера, которые не меняются.

Moodle сервер был развернут на версии 3.8, плагин Coderunner версии 4.2.3, и jobe сервер версии 1.9.0.

**Comment by MaksimOvchinnikov** [comment]
Ссылка на jobe в docker контейнере - https://github.com/trampgeek/jobeinabox
