### ISSUE TITLE
Запустить в docker-контейнере Celery + Redis

### ISSUE THREAD

**Issue by blindsphynx** [moevm/mse1h2024-coderunner#4]
Запустить Celery + Redis в отдельных docker-контейнерах. В Celery создать пока что две очереди: одну - на отправку задач из moodle для выполнения в Jobe, вторую - для отправки ответа от Jobe.

**Comment by Fayzak** [comment]
По итогу получилось запустить в отдельных контейнерах celery и redis, плюс flower и тестовый flask.
Пытался запустить таски на тестовом flask, но не получилось, таски постоянно висят в pending.
Возможно, нужно будет особым образом настроить flask и celery, однако это уже насколько я понимаю относится к задаче 6.

**Comment by Fayzak** [comment]
Требование с двумя очередями также выполнено
